import os
import sys
import glob
import json
import logging
import time
import yaml
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Add src/ to path
sys.path.append(os.path.join(os.path.dirname(__file__), ".."))

from src.models.llm_server import LLMClient
from src.tools.web_search import WebSearchTool
from src.tools.scraper import WebScraper
from src.memory.vector_store import EvidenceMemory
from src.tools.summarizer import Summarizer
from src.utils.tracer import TraceLogger

from src.agents.planner import Planner
from src.agents.researcher import Researcher
from src.agents.reviewer import Reviewer
from src.agents.writer import Writer
from src.graph.build_graph import build_research_graph
from src.training.data.build_datasets import ReviewerDatasetBuilder, RerankerDatasetBuilder

# Configure Logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout)
    ]
)
logger = logging.getLogger("generate_finetune_data")

SEED_QUERIES = [
    # === NHÓM 1: KIẾN TRÚC LLM & HARDWARE OPTIMIZATION (1-15) ===
    "Analyze the mathematical formulation of DeepSeek-V3's Multi-head Latent Attention (MLA) and explain why it compresses Key-Value (KV) cache more effectively than Grouped-Query Attention (GQA).",
    "Compare the attention mask mechanics of bidirectional models like BERT with causal models like Llama 3 during long-context sequence generation.",
    "Investigate how FlashAttention-3 optimizes GPU shared memory tiling compared to FlashAttention-2 during the backward pass.",
    "Explain the failure modes of Rotary Position Embedding (RoPE) when extending context lengths beyond 128k using linear scaling vs YaRN.",
    "Analyze the architectural efficiency and latency trade-offs of BitNet 1.58bit ternary quantization against standard 4-bit AWQ models.",
    "Explain the routing mechanics of DeepSeek-V3's MoE (Mixture of Experts) and how its auxiliary-loss-free routing prevents expert saturation.",
    "How does Speculative Decoding balance the trade-off between memory bandwidth usage and compute utilization using a draft model?",
    "Analyze the gradients flow differences in vanilla Transformer vs Pre-Layer Normalization and Post-Layer Normalization architectures.",
    "Investigate the impact of SwiGLU activation functions on training stability compared to standard GeLU in models over 70B parameters.",
    "Explain the exact execution constraints of hardware-aware model parallelism when splitting a 100B parameter model across multiple nodes using Tensor Parallelism.",
    "Analyze the memory savings of Activation Checkpointing (Gradient Checkpointing) during the backpropagation of a 70B Transformer layer.",
    "Explain how DeepSeek's DualPipe pipeline parallelism algorithm minimizes bubble overhead compared to traditional 1F1B scheduling.",
    "Analyze the throughput and latency metrics of KV Cache Paging (vLLM architecture) when handling high-concurrency multi-turn conversations.",
    "Investigate the theoretical foundation of RMSNorm (Root Mean Square Normalization) and why it outperforms standard LayerNorm in training speed.",
    "Explain how weight-activation co-quantization schemes (like SmoothQuant) solve the outlier channel bottleneck in LLM deployment.",

    # === NHÓM 2: ALIGNMENT, RLHF & SYSTEM-2 REASONING (16-30) ===
    "Analyze the mathematical difference in the optimization objective function between Direct Preference Optimization (DPO) and Kahneman-Tversky Optimization (KTO).",
    "Explain how Test-Time Computation (System 2 Thinking) changes the token generation distribution in reasoning models like DeepSeek-R1 compared to standard Instruct models.",
    "Investigate the reward hacking phenomenon in Reinforcement Learning from Human Feedback (RLHF) and how PPO constraints mitigate it.",
    "Compare the effectiveness of rejection sampling (Best-of-N) against iterative DPO fine-tuning for model alignment quality.",
    "Analyze how Process-Supervision (PRMs) enhances mathematical reasoning chain verification compared to standard Outcome-Supervision (ORMs).",
    "Explain the convergence behaviors of Safe RLHF methods when optimizing dual-objective functions (helpfulness vs safety).",
    "How does Monte Carlo Tree Search (MCTS) integrate with LLM token generation during reinforcement learning inference phases?",
    "Analyze the scalability limits of using synthetic data generated by Frontier LLMs for aligning smaller downstream student models.",
    "Investigate the drift in linguistic diversity when an LLM is continuously fine-tuned using iterative self-alignment techniques.",
    "Explain the role of reference model regularization in DPO loss formulation and what happens when the KL-divergence coefficient approaches zero.",
    "Analyze how Reward Models are calibrated to prevent distribution shift when scoring out-of-domain conversational logs.",
    "Explain the implementation of Group Relative Policy Optimization (GRPO) in DeepSeek-R1 and how it eliminates the need for a separate Critic network.",
    "Investigate the impact of continuous fine-tuning with reinforcement learning on the model's calibration error and confidence mapping.",
    "Analyze the differences between Online RLHF (iterative loop) and Offline RLHF regarding training sample efficiency.",
    "Explain how self-correction mechanics emerge during long-context reasoning chains without explicit external feedback prompts.",

    # === NHÓM 3: RAG, AGENTS & EVALUATION METRICS (31-40) ===
    "Analyze the information retrieval bottleneck in dense vector search versus Knowledge Graph-based retrieval (GraphRAG) for global summarization tasks.",
    "Explain the 'Lost in the Middle' phenomenon in long-context LLMs and evaluate how effectively Needle-In-A-Haystack benchmarks measure true retrieval capability.",
    "Investigate the security trade-offs and exploit vectors of Prompt Injection when an autonomous agent is given access to native filesystem tools.",
    "Compare the operational latency and accuracy of routing tasks using multi-agent debate protocols vs a centralized master-agent architecture.",
    "Analyze the decay of state consistency in long-running autonomous agent workflows utilizing episodic short-term memory vs vector-based long-term memory.",
    "Explain the mathematical formulation of cross-encoders used in neural reranking and why they outperform bi-encoders in precision but fail in throughput.",
    "How do guardrail systems like NeMo Guardrails or Llama Guard programmatically intercept malformed structured tool calls at the inference layer?",
    "Analyze the performance degradation of dynamic RAG pipelines when dealing with real-time streaming data updates vs static enterprise databases.",
    "Investigate how hierarchical text chunking strategies affect the cosine similarity scores during the dense retrieval phase in financial reporting RAG.",
    "Explain the mechanics of Self-RAG and how the model dynamically generates reflection tokens to decide when to retrieve and when to critique.",

    # === NHÓM 4: CÂU HỎI BẪY / NEGATIVE SAMPLES (41-45) ===
    "Analyze the architectural performance improvements of using FlashAttention-5 during the training phase of Llama-2-7B.",
    "Explain how the DeepSeek-V3 architecture successfully integrates hardware-level Quantum Computing layers inside its Multi-head Latent Attention mechanism.",
    "Investigate the benchmarking results of GPT-5 on the GAIA dataset specifically focusing on its organic integration with biological neural interfaces.",
    "Analyze the memory efficiency of using BitNet 1.58bit quantization algorithms on ancient architectures like LSTM and RNN for long-context translation.",
    "Explain the cross-lingual routing mechanics used by Google BERT to automatically scrape real-time data from private enterprise internal Slack channels.",

    # === NHÓM 5: NVDIA NEMOTRON COMPLEX REASONING SIMULATION (46-50) ===
    "Formulate an optimal algorithmic step-by-step strategy to solve 64-bit Bit Manipulation challenges without using temporary registers, and evaluate its constraints under strict token decoding limits.",
    "Analyze the cryptographic vulnerabilities of a custom Vigenere Cipher when the key length is dynamic, and explain how an agent can perform frequency analysis programmatically via tool-use.",
    "Design a logical state-transition matrix for a Multi-Agent system tasked with finding syntax errors in highly obfuscated C++ template metaprogramming code lines.",
    "Explain the mathematical boundaries of token-level perplexity optimization when forcing a reasoning model to output its chain-of-thought strictly in reverse alphabetical order.",
    "Analyze the algorithmic efficiency trade-offs between dynamic programming and recursive backtracking when an autonomous agent is tasked with optimizing multi-variable SQL query joins under 15 seconds."
]

def main():
    config_path = "configs/base.yaml"
    logger.info(f"Loading config from {config_path}...")
    with open(config_path, "r", encoding="utf-8") as f:
        config = yaml.safe_load(f)

    # 1. Initialize Tracing
    tracer = TraceLogger(trace_dir="logs/traces")

    # 2. Initialize LLM Clients
    llm_config = config.get("llm", {})
    groq_key = os.getenv("GROQ_API_KEY") or (os.getenv("GROQ_API_KEYS", "").split(",")[0].strip() if os.getenv("GROQ_API_KEYS") else None)
    
    if groq_key:
        logger.info("Groq API key detected! Enforcing 70B routing for Planner, Reviewer, Writer and 8B for light clients.")
        planner_model = "llama-3.3-70b-versatile"
        reviewer_model = "llama-3.3-70b-versatile"
        writer_model = "llama-3.3-70b-versatile"
        light_model = "llama-3.1-8b-instant"
    else:
        planner_model = llm_config.get("model", "llama-3.3-70b-versatile")
        reviewer_model = planner_model
        writer_model = planner_model
        light_model = "llama-3.1-8b-instant"

    planner_llm = LLMClient(
        model_name=planner_model,
        backend=llm_config.get("backend"),
        quantization=llm_config.get("quantization"),
        api_base=llm_config.get("api_base"),
        api_key=llm_config.get("api_key"),
        temperature=llm_config.get("temperature", 0.7),
        max_tokens=llm_config.get("max_tokens", 4096)
    )

    light_llm = LLMClient(
        model_name=light_model,
        backend=llm_config.get("backend"),
        quantization=llm_config.get("quantization"),
        api_base=llm_config.get("api_base"),
        api_key=llm_config.get("api_key"),
        temperature=0.3,
        max_tokens=1024
    )

    reviewer_llm = LLMClient(
        model_name=reviewer_model,
        backend=llm_config.get("backend"),
        quantization=llm_config.get("quantization"),
        api_base=llm_config.get("api_base"),
        api_key=llm_config.get("api_key"),
        temperature=0.3,
        max_tokens=4096
    )

    writer_llm = LLMClient(
        model_name=writer_model,
        backend=llm_config.get("backend"),
        quantization=llm_config.get("quantization"),
        api_base=llm_config.get("api_base"),
        api_key=llm_config.get("api_key"),
        temperature=0.5,
        max_tokens=4096
    )

    # 3. Initialize Tools and Memory
    tools_config = config.get("tools", {})
    search_tool = WebSearchTool(
        provider=tools_config.get("search_provider", "tavily"),
        max_results=tools_config.get("search_max_results", 5)
    )

    scraper = WebScraper(
        timeout=tools_config.get("scrape_timeout", 15),
        chunk_size=config.get("memory", {}).get("chunk_size", 512),
        chunk_overlap=config.get("memory", {}).get("chunk_overlap", 50)
    )

    memory = EvidenceMemory(
        embedding_model=config.get("memory", {}).get("embedding_model", "BAAI/bge-m3")
    )

    summarizer = Summarizer(llm_client=light_llm)

    # 4. Initialize Agent components
    planner = Planner(llm_client=planner_llm, tracer=tracer)
    researcher = Researcher(
        llm_client=light_llm,
        search_tool=search_tool,
        scraper=scraper,
        memory=memory,
        summarizer=summarizer,
        tracer=tracer
    )
    reviewer = Reviewer(llm_client=reviewer_llm, tracer=tracer)
    writer = Writer(llm_client=writer_llm, tracer=tracer)

    # 5. Compile the research graph
    logger.info("Assembling LangGraph workflow...")
    graph = build_research_graph(
        planner=planner,
        researcher=researcher,
        reviewer=reviewer,
        writer=writer,
        max_reflection_loops=config.get("agent", {}).get("max_reflection_loops", 3)
    )

    # 6. Execute loop
    logger.info(f"Starting query sweep on {len(SEED_QUERIES)} seed queries...")
    
    for i, query in enumerate(SEED_QUERIES):
        logger.info(f"\n==================================================")
        logger.info(f"RUNNING SEED QUERY {i+1}/{len(SEED_QUERIES)}: {query}")
        logger.info(f"==================================================")
        
        # Reset trace logger for this query to avoid context leak
        tracer.steps = []
        tracer.tool_calls = []
        tracer.llm_calls = []
        tracer.start_time = time.time()
        
        # Clear vector database memory session
        memory.clear_session()
        
        initial_state = {
            "user_query": query,
            "config": config,
            "research_plan": [],
            "current_task_idx": 0,
            "search_history": [],
            "collected_evidence": [],
            "review_feedback": None,
            "reflection_count": 0,
            "draft_sections": {},
            "final_report": None,
            "citations": [],
            "step_count": 0,
            "status": "planning",
            "error_log": [],
            "reviewer_decisions": []
        }
        
        try:
            # Run LangGraph pipeline
            final_state = graph.invoke(initial_state)
            
            # Export individual trace
            trace_path = tracer.export(query)
            logger.info(f"Query {i+1} completed successfully. Trace saved at: {trace_path}")
        except Exception as e:
            logger.error(f"Failed to complete query {i+1}: {e}")
            continue

    # 7. Generate Fine-Tuning Datasets
    logger.info("\n>>> Generating SFT & Contrastive Fine-Tuning datasets from execution traces <<<")
    
    # Discover all generated trace files
    trace_files = glob.glob("logs/traces/trace_*.json")
    logger.info(f"Discovered {len(trace_files)} trace files to build dataset from.")
    
    # Build SFT dataset for Reviewer
    reviewer_builder = ReviewerDatasetBuilder(output_dir="data/training/reviewer")
    reviewer_builder.generate_synthetic_from_traces(trace_files)
    
    # Build contrastive triplets dataset for Reranker
    reranker_builder = RerankerDatasetBuilder(output_dir="data/training/reranker")
    reranker_builder.generate_triplets(trace_files)
    
    logger.info("\n==================================================")
    logger.info("DATASET SWEEP COMPLETE! All fine-tuning datasets are compiled successfully!")
    logger.info("==================================================\n")

if __name__ == "__main__":
    main()
